# Generated by Django 4.1.3 on 2022-12-07 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=35)),
                ('numberOfLessons', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('intervalBetweenLessons', models.CharField(choices=[(1, '1 Week'), (2, '2 Weeks')], default=(1, '1 Week'), max_length=30)),
                ('duration', models.CharField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '1 Hour')], default=(30, '30 Minutes'), max_length=35)),
                ('teacher', models.CharField(choices=[(1, 'Mr. Gough'), (2, 'Mr. Mahendra'), (3, 'Mr. Grebenyuk'), (4, 'Mr. Thavaratnam'), (5, 'Mr. Atta')], default=(1, 'Mr. Gough'), max_length=35)),
                ('instrument', models.CharField(choices=[('Piano', 'Piano'), ('Guitar', 'Guitar'), ('Drums', 'Drums')], default=('Piano', 'Piano'), max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Student', 'Student')], default=('Student', 'Student'), max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Email must contain 5 or more characters that are all alphanumericals prior to @msms.ac.uk', regex='^\\w{5,}@msms.ac.uk$')]),
        ),
    ]
