# Generated by Django 4.1.3 on 2022-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_requestlesson_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlesson',
            name='availability',
        ),
        migrations.AddField(
            model_name='requestlesson',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='requestlesson',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='requestlesson',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '1 Hour')], default=(30, '30 Minutes')),
        ),
        migrations.AlterField(
            model_name='requestlesson',
            name='intervalBetweenLessons',
            field=models.IntegerField(choices=[(1, '1 Week'), (2, '2 Weeks')], default=(1, '1 Week')),
        ),
        migrations.AlterField(
            model_name='requestlesson',
            name='teacher',
            field=models.CharField(choices=[('Mr. Gough', 'Mr. Gough'), ('Mr. Mahendra', 'Mr. Mahendra'), ('Mr. Grebenyuk', 'Mr. Grebenyuk'), ('Mr. Thavaratnam', 'Mr. Thavaratnam'), ('Mr. Atta', 'Mr. Atta')], default=('Mr. Gough', 'Mr. Gough'), max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
